Backend: Add check for whether busybox symlink setup succeeded, fixes - fail on recoveries where symlinking our busybox environment doesn't work (CM Recovery on some devices) - use the included busybox for awk since toybox is lacking (CM Recovery)

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -15,7 +15,7 @@ ui_print() {
 }
 show_progress() { echo "progress $1 $2" > $OUTFD; }
 set_perm_recursive() {
-  dirs=$(echo $* | awk '{ print substr($0, index($0,$5)) }');
+  dirs=$(echo $* | $bb awk '{ print substr($0, index($0,$5)) }');
   for i in $dirs; do
     chown -R $1.$2 $i; chown -R $1:$2 $i;
     find "$i" -type d -exec chmod $3 {} +;
@@ -34,6 +34,8 @@ unzip -o "$ZIP";
 if [ $? != 0 -o -z "$(ls /tmp/anykernel/tools)" ]; then
   abort "Unzip failed. Aborting...";
 fi;
+chmod -R 755 /tmp/anykernel/tools /tmp/anykernel/bin;
+bb=/tmp/anykernel/tools/busybox;
 
 ### Start ACSII Txt Screen Section ####
 ui_print "_____________                            ";
@@ -90,11 +92,12 @@ if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.initd)" == 1 ]; then
 fi;
 
 ui_print "Installing kernel...";
-chmod -R 755 /tmp/anykernel/tools /tmp/anykernel/bin;
-bb=/tmp/anykernel/tools/busybox;
 for i in $($bb --list); do
   ln -s $bb /tmp/anykernel/bin/$i;
 done;
+if [ $? != 0 -o -z "$(ls /tmp/anykernel/bin)" ]; then
+  abort "Recovery busybox setup failed. Aborting...";
+fi;
 PATH="/tmp/anykernel/bin:$PATH" $bb ash /tmp/anykernel/anykernel.sh $2;
 if [ $? != "0" ]; then
   abort;
